# Generated by Django 2.0 on 2019-08-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0002_auto_20190823_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='color',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'color'}, related_name='color', to='m2m.Characteristic'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='province',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'province'}, related_name='province', to='m2m.Characteristic'),
        ),
    ]
