# Generated by Django 2.0 on 2019-08-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0003_auto_20190823_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2m.Characteristic')),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='province',
        ),
        migrations.AddField(
            model_name='plantcharacteristic',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2m.Plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='characteristics',
            field=models.ManyToManyField(blank=True, through='m2m.PlantCharacteristic', to='m2m.Characteristic'),
        ),
    ]
