# Generated by Django 2.0 on 2019-08-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0004_auto_20190826_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantcharacteristic',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='plantcharacteristic',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='plant',
            name='color',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'color'}, related_name='color', to='m2m.Characteristic'),
        ),
        migrations.AddField(
            model_name='plant',
            name='province',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'province'}, related_name='province', to='m2m.Characteristic'),
        ),
        migrations.DeleteModel(
            name='PlantCharacteristic',
        ),
    ]
