# Generated by Django 2.0 on 2019-08-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0005_auto_20190826_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='name',
        ),
        migrations.AddField(
            model_name='characteristic',
            name='constants_id',
            field=models.IntegerField(null=True),
        ),
    ]
